# Form implementation generated from reading ui file '.\.\device_select.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 540)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 961, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.device_buttons_hbx = QtWidgets.QHBoxLayout()
        self.device_buttons_hbx.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.device_buttons_hbx.setContentsMargins(32, 32, 32, 32)
        self.device_buttons_hbx.setSpacing(32)
        self.device_buttons_hbx.setObjectName("device_buttons_hbx")
        self.desktop_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.desktop_btn.setCheckable(True)
        self.desktop_btn.setAutoRepeat(True)
        self.desktop_btn.setObjectName("desktop_btn")
        self.device_buttons_hbx.addWidget(self.desktop_btn)
        self.phone_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.phone_btn.setCheckable(True)
        self.phone_btn.setAutoRepeat(True)
        self.phone_btn.setObjectName("phone_btn")
        self.device_buttons_hbx.addWidget(self.phone_btn)
        self.verticalLayout.addLayout(self.device_buttons_hbx)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.action_buttons_hbx = QtWidgets.QHBoxLayout()
        self.action_buttons_hbx.setContentsMargins(16, 16, 16, 16)
        self.action_buttons_hbx.setSpacing(0)
        self.action_buttons_hbx.setObjectName("action_buttons_hbx")
        self.cancel_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.action_buttons_hbx.addWidget(self.cancel_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.action_buttons_hbx.addItem(spacerItem1)
        self.create_project_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.create_project_btn.setEnabled(False)
        self.create_project_btn.setObjectName("create_project_btn")
        self.action_buttons_hbx.addWidget(self.create_project_btn)
        self.action_buttons_hbx.setStretch(0, 1)
        self.action_buttons_hbx.setStretch(1, 6)
        self.action_buttons_hbx.setStretch(2, 1)
        self.verticalLayout.addLayout(self.action_buttons_hbx)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.desktop_btn.setText(_translate("Form", "Персональный компьютер"))
        self.phone_btn.setText(_translate("Form", "Мобильное устройство"))
        self.cancel_btn.setText(_translate("Form", "Отмена"))
        self.create_project_btn.setText(_translate("Form", "Создать проект"))
