# Form implementation generated from reading ui file '.\.\welcome.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1281, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.projectsGrd = QtWidgets.QGridLayout()
        self.projectsGrd.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.projectsGrd.setContentsMargins(40, 40, 40, 40)
        self.projectsGrd.setSpacing(40)
        self.projectsGrd.setObjectName("projectsGrd")
        self.verticalLayout.addLayout(self.projectsGrd)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(40, 40, 40, 40)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deleteProject = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.deleteProject.setEnabled(False)
        self.deleteProject.setObjectName("deleteProject")
        self.horizontalLayout.addWidget(self.deleteProject)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.playProject = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.playProject.setEnabled(False)
        self.playProject.setObjectName("playProject")
        self.horizontalLayout.addWidget(self.playProject)
        self.editProject = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.editProject.setEnabled(False)
        self.editProject.setObjectName("editProject")
        self.horizontalLayout.addWidget(self.editProject)
        self.createProject = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.createProject.setCheckable(False)
        self.createProject.setChecked(False)
        self.createProject.setObjectName("createProject")
        self.horizontalLayout.addWidget(self.createProject)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Конструктор визуальных новелл"))
        self.label.setText(_translate("MainWindow", "Добро пожаловать"))
        self.deleteProject.setText(_translate("MainWindow", "Удалить"))
        self.playProject.setText(_translate("MainWindow", "Играть"))
        self.editProject.setText(_translate("MainWindow", "Редактировать"))
        self.createProject.setText(_translate("MainWindow", "Создать проект"))
